config/routes.rb
Rails.application.routes.draw do

  get 'profile/index'
  get 'profile/edit'
  get 'profile/update'
  
  get  'selectcreateorjoin/select'
  post 'selectcreateorjoin/decide'
  get  'selectcreateorjoin/form'
  post 'selectcreateorjoin/save_form'

  get 'homes/index'
  
  resources :chores

  def after_sign_out_path_for(resource_or_scope)
    selectcreateorjoin_select_path
  end

  devise_for :users, controllers: {
    registrations: 'registrations',
    confirmations: "confirmations"
  }

  authenticated :user do
    root to: 'homes#index', as: :authenticated_root
  end

  unauthenticated do
    root to: 'selectcreateorjoin#select'
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :chores, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chore.rb
class Chore < ApplicationRecord
  belongs_to :group
  has_many :chore_dates, dependent: :destroy

  validates :title, presence: true
  validates :cake_reward,
            presence: true,
            numericality: { only_integer: true, greater_than: 0 }
end

app/models/chore_date.rb
class ChoreDate < ApplicationRecord
  belongs_to :chore
  validates :execute_at, presence: true
  enum status: { pending: 0, done: 1 }

  # 実行日（表示用）
  def execute_date
    execute_at&.to_date
  end

  # 実行時間（表示用）
  def execute_time
    execute_at&.strftime("%H:%M")
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :users
  has_many :chores
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :group, optional: true
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :confirmable # メール確認用
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chores_controller.rb
class ChoresController < ApplicationController
  before_action :set_chore, only: [:edit, :update, :destroy]

  def index
    @chores = current_user.group.chores
  end

  def new
    @chore = Chore.new
  end

  def create
    @chore = current_user.group.chores.build(chore_params)

    dates = params[:chore][:execute_dates].split(",")
    time  = params[:chore][:execute_time]

    ActiveRecord::Base.transaction do
      @chore.save!

      dates.each do |date|
        datetime = Time.zone.parse("#{date} #{time}")

        @chore.chore_dates.create!(
          execute_at: datetime
        )
      end
    end

    redirect_to root_path, notice: "家事を登録しました"
  rescue ActiveRecord::RecordInvalid
    render :new
  end

  def edit
    # set_chore が @chore を用意してくれる
  end

  def update
    @chore = current_user.group.chores.find(params[:id])

    dates = params[:chore][:execute_dates].split(",")
    time  = params[:chore][:execute_time]

    ActiveRecord::Base.transaction do
      @chore.update!(chore_params)

      # ① 既存の実行日を全削除
      @chore.chore_dates.destroy_all

      # ② 新しい実行日を作り直す
      dates.each do |date|
        datetime = Time.zone.parse("#{date} #{time}")

        @chore.chore_dates.create!(
          execute_at: datetime
        )
      end
    end

    redirect_to @chore, notice: "更新しました"
  rescue ActiveRecord::RecordInvalid
    render :edit
  end

  def destroy
    @chore.destroy
    redirect_to chores_path, notice: "家事を削除しました"
  end

  private

  def set_chore
    @chore = current_user.group.chores.find(params[:id])
  end

  def chore_params
    params.require(:chore).permit(
      :title,
      :cake_reward,
      :detail
    )
  end
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
  def show
    super do |user|
      data = session.dig("selectcreateorjoin", "group")
      mode = session.dig("selectcreateorjoin", "mode")

      next unless data && mode

      group =
        if mode == "create"
          Group.create!(
            name: data["name"],
            passcode: data["passcode"]
          )
        else
          Group.find_by!(
            name: data["name"],
            passcode: data["passcode"]
          )
        end

      user.update!(group: group)

      session.delete("selectcreateorjoin")
    end
  end
end

app/controllers/groups/selectcreateorjoin_controller.rb
class Groups::SelectcreateorjoinController < ApplicationController
  def select
    # 表示用
  end

  def decide
    session["selectcreateorjoin"] ||= {}
    session["selectcreateorjoin"]["mode"] = params[:mode]

    redirect_to groups_selectcreateorjoin_form_path
  end

  def form
    @mode = session.dig("selectcreateorjoin", "mode")
    redirect_to groups_selectcreateorjoin_select_path unless @mode
  end

  def save_form
    session["selectcreateorjoin"]["group"] = {
      "name"     => params[:group_name],
      "passcode" => params[:passcode]
    }

    redirect_to new_user_registration_path
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
  end

  def edit
  end

  def update
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def create
    build_resource(sign_up_params)

    user_data = session.dig("selectcreateorjoin", "user")
    if user_data
      resource.name = user_data["name"]
      resource.icon = user_data["icon"]
    end

    if resource.save
      sign_up(resource_name, resource)
      redirect_to root_path, notice: "確認メールを送信しました"
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/controllers/selectcreateorjoin_controller.rb
class SelectcreateorjoinController < ApplicationController
  def select
    # 表示用
  end

  def decide
    session["selectcreateorjoin"] ||= {}
    session["selectcreateorjoin"]["mode"] = params[:mode]

    redirect_to selectcreateorjoin_form_path
  end

  def form
    @mode = session.dig("selectcreateorjoin", "mode")
    redirect_to selectcreateorjoin_select_path unless @mode
  end

  def save_form
    session["selectcreateorjoin"] ||= {}

    session["selectcreateorjoin"]["user"] = {
      "name" => params[:name],
      "icon" => params[:icon]
    }

    session["selectcreateorjoin"]["group"] = {
      "name"     => params[:group_name],
      "passcode" => params[:passcode]
    }

    redirect_to new_user_registration_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chores_helper.rb
module ChoresHelper
end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/chores/_form.html.erb
<%= form_with model: @chore, local: true do |f| %>

  <div>
    <%= f.label :title, "家事名" %><br>
    <%= f.text_field :title %>
  </div><br>

  <div>
    <%= f.label :cake_reward, "ショートケーキ獲得数" %><br>
    <%= f.number_field :cake_reward, min: 1 %>
  </div><br>

  <div>
    <%= f.text_field :execute_dates,
      id: "execute_dates",
      value: @chore.chore_dates
                    .order(:execute_at)
                    .map { |cd| cd.execute_date }
                    .join(",") %>
  </div><br>

  <div>
    <%= f.label :execute_time, "実行時間" %><br>
    <%= f.time_field :execute_time,
      value: @chore.chore_dates.first&.execute_time %>
  </div><br>

  <div>
    <%= f.label :detail, "家事の詳細" %><br>
    <%= f.text_area :detail, rows: 4 %>
  </div><br>

  <%= f.submit %>

<% end %>

app/views/chores/create.html.erb
<h1>Chores#create</h1>
<p>Find me in app/views/chores/create.html.erb</p>

app/views/chores/edit.html.erb
<% content_for :header_title do %>
  家事変更
<% end %>

<h1>家事変更</h1>

<%= render "form" %>

<div style="text-align: left;">
  <%= link_to "戻る", chores_path %>
</div

app/views/chores/index.html.erb
<% content_for :header_title do %>
  家事リスト
<% end %><br>

<div class="chore-list">
  <% @chores.each do |chore| %>
    <div class="chore-row">

      <div class="chore-title-detail">
        <span class="chore-title"><%= chore.title %></span>
        <span class="chore-detail">
          <%= truncate(chore.detail, length: 30) %>
        </span>
      </div>

      <div class="chore-cake-reward">
        <%= chore.cake_reward %> pt
      </div>

      <div class="chore-actions">
        <%= link_to "編集", edit_chore_path(chore), class: "edit-link" %>
        <%= link_to "削除",
                    chore_path(chore),
                    data: { turbo_method: :delete, turbo_confirm: "削除しますか？" },
                    class: "delete-link" %>
      </div>
    </div>
  <% end %>
</div><br>

<div style="text-align: right;">
  <%= link_to "戻る", homes_index_path %>
</div

app/views/chores/new.html.erb
<% content_for :header_title do %>
  家事登録
<% end %>

<h1>家事登録</h1>

<%= render "form" %>

<div style="text-align: left;">
  <%= link_to "戻る", homes_index_path %>
</div

app/views/groups/selectcreateorjoin/form.html.erb
<h1>
  <%= @mode == "create" ? "グループを作成する" : "グループに参加する" %>
</h1>

<%= form_with url: groups_selectcreateorjoin_save_form_path, method: :post do %>

  <h2>あなたの情報</h2>

  <div>
    <label>名前</label>
    <%= text_field_tag :name %>
  </div>

  <div>
    <label>アイコン</label>
    <%= select_tag :icon,
      options_for_select([["🐶", "dog"], ["🐱", "cat"], ["🐼", "panda"]]) %>
  </div>

  <h2>グループ情報</h2>

  <div>
    <label>グループ名</label>
    <%= text_field_tag :group_name %>
  </div>

  <div>
    <label>合言葉</label>
    <%= password_field_tag :passcode %>
  </div>

  <%= submit_tag "次へ（ユーザー登録）" %>

<% end %>

app/views/groups/selectcreateorjoin/select.html.erb
<h1>グループを作成するか、参加するか選択してください</h1>

<%= form_with url: groups_selectcreateorjoin_decide_path, method: :post, local: true do %>
  <%= hidden_field_tag :mode, "create" %>
  <%= submit_tag "グループを作成する" %>
<% end %>

<%= form_with url: groups_selectcreateorjoin_decide_path, method: :post, local: true do %>
  <%= hidden_field_tag :mode, "join" %>
  <%= submit_tag "グループに参加する" %>
<% end %>

<%= link_to "ログイン", new_user_session_path %>





app/views/homes/index.html.erb
<% content_for :header_title do %>
  ホーム
<% end %>
<% content_for :header_right do %>
  <%= link_to "プロフ", profile_index_path %>
<% end %>

<h1>ホーム</h1>

<%= link_to "家事リスト", chores_path %><br><br>

<%= link_to "家事を登録する", new_chore_path %>

app/views/layouts/_header.html.erb
<header style="background: #e6f2ee; padding: 12px; display: flex; justify-content: space-between;">
  <div>
    <%= content_for?(:header_left) ? yield(:header_left) : "ロゴ" %>
  </div>

  <strong>
    <%= content_for?(:header_title) ? yield(:header_title) : "" %>
  </strong>

  <div>
    <%= content_for?(:header_right) ? yield(:header_right) : "" %>
  </div>
</header>


app/views/layouts/application.html.erb
<head>
  <title>HouseworkApp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body>
  <% if notice %>
    <div class="notice"><%= notice %></div>
  <% end %>

  <% if alert %>
    <div class="alert"><%= alert %></div>
  <% end %>
  <%= render "layouts/header" %>
  <%= javascript_importmap_tags %>
  <%= yield %>
</body>

app/views/selectcreateorjoin/form.html.erb
<h1>
  <%= @mode == "create" ? "グループを作成する" : "グループに参加する" %>
</h1>

<%= form_with url: selectcreateorjoin_save_form_path, method: :post do %>

  <h2>ユーザー情報</h2>

  <div>
    <label>ニックネーム</label>
    <%= text_field_tag :name %>
  </div>

  <div>
    <label>アイコン</label>
    <%= select_tag :icon,
      options_for_select([["🐶", "dog"], ["🐱", "cat"], ["🐼", "panda"]]) %>
  </div><br><br>

  <h2>グループ情報</h2>

  <div>
    <label>グループ名</label>
    <%= text_field_tag :group_name %>
  </div>

  <div>
    <label>合言葉</label>
    <%= password_field_tag :passcode %>
  </div>

  <%= submit_tag "次へ（ユーザー登録）" %>

<% end %>

app/views/selectcreateorjoin/select.html.erb
<% content_for :header_right do %>
  <%= link_to "ログイン", user_session_path %>
<% end %>

<h1>グループを作成するか、参加するか選択してください</h1>

<%= form_with url: selectcreateorjoin_decide_path, method: :post, local: true do %>
  <%= hidden_field_tag :mode, "create" %>
  <%= submit_tag "グループを作成する" %>
<% end %>

<%= form_with url: selectcreateorjoin_decide_path, method: :post, local: true do %>
  <%= hidden_field_tag :mode, "join" %>
  <%= submit_tag "グループに参加する" %>
<% end %>
